export enum BadgeType {
    EMPTY_BADGE = 'EMPTY_BADGE',
    FAIL_BADGE = 'FAIL_BADGE',
    SUCCESS_BADGE = 'SUCCESS_BADGE',
    DROUGHT_BADGE = 'DROUGHT_BADGE',
    FLOOD_BADGE = 'FLOOD_BADGE',
    WILDLIFE_BADGE = 'WILDLIFE_BADGE',
    NULL = ''
}
